### ISSUE TITLE
Sveltekit / Server-side Rendering Support

### ISSUE THREAD

**Issue by eric-cakework** [salte-auth/salte-auth#546]
Hi - Does this package work with Sveltekit? I have a basic Sveltekit app set up and the SalteAuth import fails with the following error.

Thanks!

`
import { SalteAuth } from "@salte-auth/salte-auth";
`

ReferenceError: self is not defined
    at /Users/ericchen/Projects/sahale/frontend/node_modules/@salte-auth/salte-auth/dist/salte-auth.min.js:8:28373
    at /Users/ericchen/Projects/sahale/frontend/node_modules/@salte-auth/salte-auth/dist/salte-auth.min.js:8:69
    at Object.<anonymous> (/Users/ericchen/Projects/sahale/frontend/node_modules/@salte-auth/salte-auth/dist/salte-auth.min.js:8:233)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)

**Comment by cecilia-sanare** [comment]
I've honestly never heard of Sveltekit prior to this point. 
If it utilizes server-side rendering then support was never implemented in this project to make that possible.

`salte-auth` and all of its sub-projects are effectively in maintenance mode at the moment and as such new features aren't really being implemented.

I'll keep this issue open as a way of tracking support regardless however :3

**Comment by eric-cakework** [comment]
Makes sense. I suspect there's some work to get things working with Vite. Thanks for the prompt response and heads up!

**Comment by wolfie82** [comment]
Is the long tail of maintenance mode to eventually archive the project?  No worries either way, I'm just trying to understand the direction.  Meaning are you feature complete, and only doing bug fixes?  However, the project is still very much active.

This is a great library.  Thank you for your efforts!

**Comment by cecilia-sanare** [comment]
@wolfie82 

At this point we're considering it feature complete and just implementing bug fixes. 

The primary reason I'm keeping feature requests around in spite of that is if I ever decide to recreate this project from scratch on my own.

However, at this point, I'm not ready to commit to owning a library like `salte-auth`. 

Hopefully this provides a little more clarity around the projects state! ❤️
